### ISSUE TITLE
CategoricalEncoding returns NULL

### ISSUE THREAD

**Issue by inoddy** [AdrianAntico/Rodeo#1]
I'd like to try CategoricalEncoding but the sample code does not work. 

data <- AutoQuant::CategoricalEncoding(
  data = data,
  ML_Type = "classification",
  GroupVariables = paste0("Factor_", 1:10),
  TargetVariable = "Adrian",
  Method = Meth[MethNum],
  SavePath = getwd(),
  Scoring = FALSE,
  ReturnFactorLevelList = FALSE,
  SupplyFactorLevelList = NULL,
  KeepOriginalFactors = FALSE)

AutoQuant no longer has CategoricalEncoding. And when Rodeo::CategoricalEncoding is used instead the function returns NULL

**Comment by AdrianAntico** [comment]
@inoddy Thanks for letting me know about the issue. I recently moved these feature engineering functions to a separate package (Rodeo) from AutoQuant. Looks like I didn't update the package references, however, when it came to running the examples. 

Also, I had removed the m_estimator type of encoding from the Categorical Encoding function a while back but didn't update the examples that called for it to run. Can you try running it again?

**Comment by inoddy** [comment]
The m_estimator was the problem. I didn't realise that if I tried the others it would have worked. Maybe you need to raise an error if a non valid input is used. Anyway, it all seems to be working now. Appreciate the quick fix.

**Comment by AdrianAntico** [comment]
@inoddy Yes, that makes sense. I will update the function(s) to ensure that.

**Comment by AdrianAntico** [comment]
@inoddy Okay, I updated that one function to return data as is back to the user if they get the method name wrong. Question - are you interested in contributing? This package has a lot of potential...

**Comment by inoddy** [comment]
I'm interested in the topic so contributions are a possibility. What did you have in mind? I have an interest in high-cardinality categoricals

**Comment by AdrianAntico** [comment]
High cardinality categorical methods are certainly welcome
